# Generated by Django 4.2.19 on 2025-02-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesort', '0002_user_alter_snippet_title_sharedsnippet_fragment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
