# Generated by Django 4.2.19 on 2025-02-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesort', '0004_alter_snippet_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
